services:
  - type: web
    name: number-info-bot
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
